function p = smc_params(p)
% =========================================================================
% smc_params.m — Retuned SMC Gains for 3D Lissajous Figure-8 Trajectory
% =========================================================================
%
% TUNING RATIONALE (vs original gains)
% ─────────────────────────────────────
% Original problem: x/y errors ≈ ±0.2 / ±0.5 m, never settling.
% Root cause: outer-loop cascade (kpx, kdx) too weak to keep up with the
% Lissajous trajectory (omega=0.5 rad/s for x, 1.0 rad/s for y).
%
% The XY loop works as follows:
%   vel_ref  = kp * (x_des - x)          position error → velocity ref
%   accel_ref = kd * (vel_ref - x_dot)   velocity error → accel ref
%   Ux = (m/U1) * (accel_ref + c*e_dot + ks*sat + kl*s)
%
% For the Lissajous:
%   x requires bandwidth ~ omega     = 0.5 rad/s  → needs kpx ~ 1.5-2.0
%   y requires bandwidth ~ 2*omega   = 1.0 rad/s  → needs kpy ~ 3.0-4.0
%
% Fix strategy:
%   1. Raise kpx/kpy and kdx/kdy significantly (primary fix)
%   2. Raise c_x/c_y to steepen sliding surface (faster error closure)
%   3. Raise ks_x/ks_y slightly for stronger switching action
%   4. Add small kl_x/kl_y for smooth convergence inside boundary layer
%   5. Tighten sat_bl slightly for sharper surface enforcement
%   6. Raise attitude gains slightly to handle larger phi/theta commands
%
% EXPECTED IMPROVEMENT
% ────────────────────
%   RMSE x   : 0.159 → ~0.05–0.08 m
%   RMSE y   : 0.281 → ~0.08–0.15 m   (y harder: 2x frequency)
%   RMSE z   : already good; kept ~same
%   phi/theta settle: should settle once position tracks
%
% =========================================================================

    % ── XY outer-loop cascade gains ───────────────────────────────────────
    % Raised substantially to match Lissajous bandwidth.
    % Rule of thumb: kp > 2*omega for the axis frequency.
    % x-axis: omega = 0.5 rad/s  → kpx = 2.0, kdx = 1.5
    % y-axis: omega = 1.0 rad/s  → kpy = 3.5, kdy = 2.0
    p.kpx = 2.0;    % was 0.7
    p.kpy = 3.5;    % was 0.7
    p.kdx = 1.5;    % was 0.5
    p.kdy = 2.0;    % was 0.5

    % ── Altitude (z) ──────────────────────────────────────────────────────
    % Already performing well (settled at 8.38s). Small increase to c_z
    % for faster initial rise; ks_z and kl_z kept conservative.
    p.c_z   = 0.8;  % was 0.5  — faster surface approach
    p.ks_z  = 0.5;  % was 0.4
    p.kl_z  = 0.3;  % was 0.2

    % ── X position ────────────────────────────────────────────────────────
    % c_x raised to match the higher outer-loop bandwidth.
    % ks_x raised for stronger switching; kl_x added for smooth closure.
    p.c_x   = 1.0;  % was 0.5
    p.ks_x  = 0.6;  % was 0.4
    p.kl_x  = 0.2;  % was 0.1

    % ── Y position ────────────────────────────────────────────────────────
    % Y has 2x frequency so needs higher c_y and ks_y than x.
    p.c_y   = 1.5;  % was 0.5
    p.ks_y  = 0.8;  % was 0.4
    p.kl_y  = 0.2;  % was 0.1

    % ── Roll (phi) ────────────────────────────────────────────────────────
    % Slightly raised c_phi for faster attitude response to larger phi_cmd
    % excursions generated by the stronger XY outer loop.
    p.c_phi   = 1.5;  % was 1.0
    p.ks_phi  = 0.4;  % was 0.3
    p.kl_phi  = 0.05; % was 0.0  — small linear term for smooth closure

    % ── Pitch (theta) ─────────────────────────────────────────────────────
    p.c_theta  = 1.5;  % was 1.0
    p.ks_theta = 0.4;  % was 0.3
    p.kl_theta = 0.05; % was 0.0

    % ── Yaw (psi) ─────────────────────────────────────────────────────────
    % Yaw already excellent — kept unchanged.
    p.c_psi   = 0.5;
    p.ks_psi  = 0.1;
    p.kl_psi  = 0.3;

    % ── Boundary layer ────────────────────────────────────────────────────
    % Tightened slightly: faster surface enforcement, still chattering-free.
    p.sat_bl = 0.10;  % was 0.15

end